# Generated by Django 3.1 on 2023-12-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catogries', '0004_category_id'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='opinion',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='username',
        ),
        migrations.AddField(
            model_name='review',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Catogries.category'),
        ),
    ]
