# Generated by Django 3.1 on 2023-12-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_auto_20231217_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='flower',
        ),
    ]
