# Generated by Django 3.1 on 2023-12-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_review_flower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='flower',
        ),
    ]
