# Generated by Django 3.1 on 2023-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_auto_20231218_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='flower',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
