# Generated by Django 3.1 on 2023-12-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catogries', '0004_category_id'),
        ('Reviews', '0008_auto_20231218_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Catogries.category'),
        ),
    ]
