# Generated by Django 3.1 on 2023-12-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0010_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
