# Generated by Django 3.1 on 2023-12-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='Username',
        ),
    ]
