# Generated by Django 3.1 on 2023-12-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20231216_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
    ]
