# Generated by Django 3.1 on 2023-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catogries', '0002_auto_20231203_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ID',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/'),
        ),
    ]
