# Generated by Django 3.1 on 2023-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catogries', '0003_auto_20231210_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
